networks:
  redpanda_network:
    driver: bridge
    ipam:
      config:
      - subnet: "172.24.1.0/24"
        gateway: "172.24.1.1"
services:
  redpanda_source:
    image: 310638889487.dkr.ecr.us-west-2.amazonaws.com/docker.redpanda.com/redpandadata/redpanda:v24.3.5
    container_name: redpanda_source
    command:
      - redpanda
      - start
      - --kafka-addr
      - internal://0.0.0.0:9092,external://172.24.1.10:19092
      - --advertise-kafka-addr
      - internal://172.24.1.10:9092,external://127.0.0.1:19092
      - --smp 1
      - --memory 1G
      - --mode dev-container
      - --set redpanda.auto_create_topics_enabled=true
      - "--set redpanda.kafka_api_tls={\
          'name':'internal','enabled':true,'require_client_auth':true,\
          'cert_file':'/etc/redpanda/certs/src.crt',\
          'key_file':'/etc/redpanda/certs/src.key',\
          'truststore_file':'/etc/redpanda/certs/ca.crt'}"
      - "--set redpanda.admin_api_tls={\
          'name':'internal','enabled':true,'require_client_auth':true,\
          'cert_file':'/etc/redpanda/certs/src.crt',\
          'key_file':'/etc/redpanda/certs/src.key',\
          'truststore_file':'/etc/redpanda/certs/ca.crt'}"
    networks:
      redpanda_network:
        ipv4_address: "172.24.1.10"
    volumes:
      - ./certs:/etc/redpanda/certs
      - ./redpanda-edge-agent:/usr/local/bin/redpanda-edge-agent
      - ./agent.yaml:/etc/redpanda/agent.yaml
      - ./supervisor.conf:/etc/supervisord.conf
    ports:
      - "19092:19092"
      - "19644:9644"
      - "18081:8081"
  redpanda_destination:
    image: 310638889487.dkr.ecr.us-west-2.amazonaws.com/docker.redpanda.com/redpandadata/redpanda:v24.3.5
    container_name: redpanda_destination
    command:
      - redpanda
      - start
      - --kafka-addr
      - internal://0.0.0.0:9092,external://172.24.1.20:29092
      - --advertise-kafka-addr
      - internal://172.24.1.20:9092,external://127.0.0.1:29092
      - --smp 1
      - --memory 1G
      - --mode dev-container
      - --set redpanda.auto_create_topics_enabled=true
      - "--set redpanda.kafka_api_tls={\
          'name':'internal','enabled':true,'require_client_auth':true,\
          'cert_file':'/etc/redpanda/certs/dst.crt',\
          'key_file':'/etc/redpanda/certs/dst.key',\
          'truststore_file':'/etc/redpanda/certs/ca.crt'}"
      - "--set redpanda.admin_api_tls={\
          'name':'internal','enabled':true,'require_client_auth':true,\
          'cert_file':'/etc/redpanda/certs/dst.crt',\
          'key_file':'/etc/redpanda/certs/dst.key',\
          'truststore_file':'/etc/redpanda/certs/ca.crt'}"
    networks:
      redpanda_network:
        ipv4_address: "172.24.1.20"
    volumes:
      - ./certs:/etc/redpanda/certs
    ports:
      - "29092:29092"
      - "29644:9644"
      - "28081:8081"
    
  redpanda_edge_agent:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: redpanda_edge_agent
    depends_on:
      - redpanda_source
      - redpanda_destination
    environment:
      # all env vars passed in that the container requires need to be specified in this section
      # Only set the variables that are specific to the docker-compose environment
      # the remainder will come from the default service_configuration.env file
      - DD_SERVICE=redpanda-edge-agent
      - DD_ENV=local
      - DD_VERSION=1.0.4
      - DD_TRACE_OTLP_ENABLED=true
      - DD_OTLP_TRACES_URL=datadog-agent:4317
      - DD_AGENT_HOST=datadog-agent
    networks:
      redpanda_network:
        ipv4_address: "172.24.1.30"
    volumes:
      - ./agent.yaml:/etc/redpanda/agent.yaml
      - ./certs:/etc/redpanda/certs

# enable to test datadog locally
  datadog-agent:
    image: datadog/agent:latest 
    expose:
      - "4317"
    ports:
      - "4317:4317"
    environment:
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_AC_EXCLUDE=name:datadog-agent
      - DD_API_KEY=no_key # Use the dev-testing-key API key here (https://app.datadoghq.com/organization-settings/api-keys)
      - DD_ENV=local
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    networks:
      - redpanda_network
    healthcheck:
      test: [ "NONE" ]


